### ISSUE TITLE
What's your version of NDK ?

### ISSUE THREAD

**Issue by Menee** [yamsam/Qt5Caffe2AndroidDemo#2]
I tried on pytorch v1.1.0, ndk 19, arm64, api level 28, however it failed.

It said 'File already exists in database: caffe2.proto' on my debug window and the logcat said
'''
5-27 10:39:02.979 26708 26727 E libc++abi: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
05-27 10:39:03.097 26730 26730 F DEBUG   : Abort message: '[libprotobuf FATAL /home/weihao/Sources/pytorch-total-v1.1/pytorch/third_party/protobuf/src/google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): '
'''

Do you have any idea on the issue ?
or could you please tell me what is the version of you ndk so that I can use your precompiled libraries.

**Comment by yamsam** [comment]
I haven't tried to compile my code with recent pytorch v1.1.0, so i don't have any idea to solve it.

I used android-ndk-r16b  and Caffe 0.8.1(before merged into pyrorch) to compile my code.

**Comment by Menee** [comment]
Thanks a lot.
